#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the 8x8 katakana glyph table for the Matrix screensaver AND render
preview frames of both BT screensavers with the exact same algorithms.

Outputs
  katakana8x8.h      - C table (PROGMEM) consumed by cyd-album-v2.ino
  mockup_saver.png   - 2x preview of Life + Matrix (before/after a few frames)
"""
import os, random
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
KATA = "アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン"
DIGITS = "0123456789"
CHARS = KATA + DIGITS
FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/fonts-japanese-gothic.ttf",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/opentype/noto/NotoSerifCJK-Bold.ttc",
]


def load_font(size):
    for p in FONT_CANDIDATES:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, size)
            except Exception:
                continue
    raise SystemExit("no CJK font found")


def raster(ch, font, size=8, thresh=90):
    """Render one char centred on an 8x8 canvas -> 8 row bytes (MSB = left)."""
    pad = size * 2
    img = Image.new("L", (pad, pad), 0)
    d = ImageDraw.Draw(img)
    d.text((pad // 2, pad // 2), ch, font=font, fill=255, anchor="mm")
    bbox = img.getbbox()
    if bbox:
        img = img.crop(bbox)
    # nearest-neighbour fit into 8x8, keeping aspect
    w, h = img.size
    scale = min(8 / w, 8 / h)
    nw, nh = max(1, round(w * scale)), max(1, round(h * scale))
    img = img.resize((nw, nh), Image.NEAREST)
    canvas = Image.new("L", (8, 8), 0)
    canvas.paste(img, ((8 - nw) // 2, (8 - nh) // 2))
    rows = []
    for y in range(8):
        b = 0
        for x in range(8):
            if canvas.getpixel((x, y)) >= thresh:
                b |= 1 << (7 - x)
        rows.append(b)
    return rows, sum(bin(r).count("1") for r in rows)


best = None
for size in (9, 10, 11, 8):
    font = load_font(size)
    table, inks = [], []
    for ch in CHARS:
        rows, ink = raster(ch, font)
        table.append(rows)
        inks.append(ink)
    ok = sum(1 for i in inks if 4 <= i <= 34)
    print(f"size {size}: glyphs in range {ok}/{len(CHARS)}  min={min(inks)} max={max(inks)}")
    score = ok * 100 - abs(sum(inks) / len(inks) - 14)
    if best is None or score > best[0]:
        best = (score, size, table, inks)

score, size, table, inks = best
print("chosen font size:", size, "| ink avg %.1f" % (sum(inks) / len(inks)))

# ── emit the C header ─────────────────────────────────────────────────────
with open(os.path.join(HERE, "katakana8x8.h"), "w") as f:
    f.write("// Auto-generated by tools/make_katakana.py - 8x8 katakana + digits for the\n")
    f.write("// Matrix screensaver. One byte per row, MSB = leftmost pixel; draw with\n")
    f.write("// tft.drawBitmap(x, y, KATA8[g], 8, 8, colour).\n")
    f.write("#pragma once\n#include <pgmspace.h>\n")
    f.write(f"#define KATA8_N {len(CHARS)}\n")
    f.write("static const uint8_t KATA8[KATA8_N][8] PROGMEM = {\n")
    for ch, rows in zip(CHARS, table):
        f.write("  {%s},  // %s\n" % (", ".join("0x%02X" % r for r in rows), ch))
    f.write("};\n")
print("wrote katakana8x8.h |", len(CHARS), "glyphs |", len(CHARS) * 8, "bytes")

# ── shared simulators (same constants as the firmware) ────────────────────
SCR_W, SCR_H = 240, 320
BG = (12, 12, 16)
LIFE_W, LIFE_H, CELL = 60, 80, 4   # full panel, matches the firmware
LIFE_COL = (88, 190, 245)
MX_COLS, MX_ROWS, MX_PX, MX_PY = 20, 32, 12, 10
MX_LEVELS = [(210, 255, 210), (60, 230, 110), (30, 170, 70), (20, 110, 45), (14, 60, 28)]


def glyph_px(rows):
    return [(x, y) for y in range(8) for x in range(8) if rows[y] & (1 << (7 - x))]


GLY = [glyph_px(r) for r in table]


def life_blank():
    return [[random.random() < 0.28 for _ in range(LIFE_W)] for _ in range(LIFE_H)]


def life_step(g):
    n = [[False] * LIFE_W for _ in range(LIFE_H)]
    for y in range(LIFE_H):
        for x in range(LIFE_W):
            c = 0
            for dy in (-1, 0, 1):
                for dx in (-1, 0, 1):
                    if dx == 0 and dy == 0:
                        continue
                    if g[(y + dy) % LIFE_H][(x + dx) % LIFE_W]:
                        c += 1
            n[y][x] = (c == 3) or (c == 2 and g[y][x])
    return n


def draw_life(g, img):
    d = ImageDraw.Draw(img)
    for y in range(LIFE_H):
        for x in range(LIFE_W):
            if g[y][x]:
                d.rectangle([x * CELL, y * CELL, x * CELL + CELL - 1, y * CELL + CELL - 1], fill=LIFE_COL)


def matrix_state():
    head = [random.randrange(MX_ROWS) for _ in range(MX_COLS)]
    length = [random.randint(4, 16) for _ in range(MX_COLS)]
    cells = [[None] * MX_ROWS for _ in range(MX_COLS)]
    for c in range(MX_COLS):
        for k in range(length[c]):
            r = (head[c] - k) % MX_ROWS
            cells[c][r] = (random.randrange(len(CHARS)), k)
    return head, length, cells


def matrix_step(head, length, cells):
    for c in range(MX_COLS):
        head[c] = (head[c] + 1) % MX_ROWS
        # age the trail
        for r in range(MX_ROWS):
            if cells[c][r] is not None:
                g, age = cells[c][r]
                cells[c][r] = (g, age + 1) if age + 1 <= length[c] else None
        cells[c][head[c]] = (random.randrange(len(CHARS)), 0)
    return head, length, cells


def draw_matrix(head, length, cells, img):
    d = ImageDraw.Draw(img)
    for c in range(MX_COLS):
        for r in range(MX_ROWS):
            if cells[c][r] is None:
                continue
            g, age = cells[c][r]
            col = MX_LEVELS[age] if age < len(MX_LEVELS) else MX_LEVELS[-1]
            x, y = c * MX_PX + 2, r * MX_PY + 1
            for (gx, gy) in GLY[g]:
                d.point((x + gx, y + gy), fill=col)


random.seed(7)
# Life: run 40 generations, show the 40th frame
life = life_blank()
for _ in range(40):
    life = life_step(life)
img_life = Image.new("RGB", (SCR_W, SCR_H), BG)
draw_life(life, img_life)

heads, lens, cells = matrix_state()
for _ in range(25):
    heads, lens, cells = matrix_step(heads, lens, cells)
img_mx = Image.new("RGB", (SCR_W, SCR_H), BG)
draw_matrix(heads, lens, cells, img_mx)

S, PAD, LH = 2, 10, 16
cw, ch = SCR_W * S, SCR_H * S
sheet = Image.new("RGB", (PAD + 2 * (cw + PAD), PAD + ch + LH + PAD), (24, 24, 28))
dr = ImageDraw.Draw(sheet)
for i, (lab, im) in enumerate((("Screensaver 1 - Conway's Game of Life", img_life),
                               ("Screensaver 2 - Matrix digital rain (katakana)", img_mx))):
    x = PAD + i * (cw + PAD)
    dr.text((x + 2, 2), lab, fill=(230, 230, 235))
    sheet.paste(im.resize((cw, ch), Image.NEAREST), (x, LH))
out = os.path.join(HERE, "mockup_saver.png")
sheet.save(out)
print(out, sheet.size)
