#!/usr/bin/env python3
"""Convert three WAV chimes into cyd-album-v2/jingles_pcm.h (PCM embedded in flash).

Usage:
    python3 tools/make_jingles.py boot.wav connect.wav disconnect.wav

Each input is mixed down to mono, stripped of leading/trailing silence, peak
normalised to -1 dBFS and written as mono 16-bit PCM @ 44100 Hz. The generated
header is ~1.9 MB of source text (~750 KB of PCM) and pushes the app image to
~83% of the 3 MB partition, so re-run it only when the chimes really change.
Firmware source priority at runtime: /sounds/*.wav on SD -> embedded PCM ->
procedural chime.
"""
import sys, wave
import numpy as np

OUT = "cyd-album-v2/jingles_pcm.h"
VARS = [("J_BOOT_PCM", "boot"), ("J_CONN_PCM", "connect"), ("J_DISC_PCM", "disconnect")]


def load(path, target_sr=44100):
    w = wave.open(path, "rb")
    sr, ch, n = w.getframerate(), w.getnchannels(), w.getnframes()
    d = np.frombuffer(w.readframes(n), dtype="<i2").astype(np.float32)
    w.close()
    if ch == 2:
        d = d.reshape(-1, 2).mean(1)
    d /= 32768.0
    if sr != target_sr:  # nearest-neighbour resample
        idx = (np.arange(int(len(d) * target_sr / sr)) * sr / target_sr).astype(int)
        d = d[np.clip(idx, 0, len(d) - 1)]
    # trim leading/trailing silence (threshold 2% of peak, 10 ms frames)
    hop = int(0.01 * target_sr)
    env = np.array([np.sqrt((d[i:i + hop] ** 2).mean() + 1e-12)
                    for i in range(0, len(d) - hop, hop)])
    nz = np.nonzero(env > max(env.max() * 0.02, 3e-4))[0]
    if len(nz):
        d = d[max(0, (nz[0] - 3) * hop):min(len(d), (nz[-1] + 8) * hop)]
    peak = np.abs(d).max() or 1.0
    return (d / peak * 0.90 * 32767).astype("<i2")  # -1 dBFS


def main(paths):
    if len(paths) != 3:
        sys.exit(__doc__)
    out = ["// Auto-generated by tools/make_jingles.py - do not edit by hand.",
           "// Mono 16-bit PCM @ 44100 Hz, peak-normalised to -1 dBFS.",
           "// Source WAVs: %s" % ", ".join(paths), "#pragma once",
           "#include <Arduino.h>", ""]
    lens, ptrs = [], []
    for (var, name), path in zip(VARS, paths):
        d = load(path)
        lens.append(len(d))
        ptrs.append(var)
        out.append("static const int16_t %s[%d] PROGMEM = {" % (var, len(d)))
        for i in range(0, len(d), 20):
            out.append(",".join(str(int(x)) for x in d[i:i + 20]) + ",")
        out.append("};")
        out.append("")
        print("%-8s %s -> %d samples (%.2f s)" % (name, path, len(d), len(d) / 44100.0))
    out += ["#define JINGLE_EMB_RATE 44100",
            "static const uint32_t JINGLE_EMB_LEN[3] = {%s};" % ", ".join(map(str, lens)),
            "static const int16_t* const JINGLE_EMB_PTR[3] = {%s};" % ", ".join(ptrs)]
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main(sys.argv[1:])
